# To auto-connect to Wi-Fi
#CIRCUITPY_WIFI_SSID="yourwifissid"
#CIRCUITPY_WIFI_PASSWORD="yourpassword"

# To enable modifying files from the web. Change this too!
# Leave the User field blank when you type the password into the browser.
#CIRCUITPY_WEB_API_PASSWORD="passw0rd"

#CIRCUITPY_WEB_API_PORT=80